# https://taskfile.dev

version: '3'

tasks:
  up:
    cmds:
      - docker-compose up -d --build --force-recreate

  lazy-up:
    cmds:
      - task up
    status:
      - test -n "$(docker-compose ps -q jupyter)"

  down:
    cmds:
      - docker-compose down

  default:
    deps: [lazy-up]
    cmds:
      - docker-compose exec jupyter bash 
    silent: true
